### ISSUE TITLE
Bump fee UX issues

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#100]
Bump fee works! Here are some improvement.

- [x] When bumping fee, show fee selection cards (fastest, fast, medium slow)
- [x] When sending, no need to have "build transaction" and "send transaction" buttons. Should only have a "Bump Fee" button, which automatically builds and sends the new transaction.
- [x] When trying to bump the fee twice, the second time I get error "null"
- [x] When bumping the transaction, the "send transaction" button shows a loading icon and it seems to be an infinite load. If I click the back button, it goes back to the transaction, and I can see that it has been bumped.
- [x] I noticed that there is no success message after the transaction is bumped (see above issue)

**Comment by i5hi** [comment]
- [ ] Imported wallets do not recognize RBF transactions

We currently mark a tx RBF at the time of Send and store that info in our local Transaction model. If we delete the wallet and re-import it, rbfEnabled defaults to false. 

We should try to get RBF status from bdkTx so even imported wallets can recognize RBF.
