### ISSUE TITLE
"Request payment" not working

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#103]
As of latest version, the "Request payment" feature in "Receive Bitcoin" page is not working.
I click it, it shows the "Request a payment" pop-up, I add the amount and the public description, I click save, nothing happens when I click save. I close the pop-up and the page has not been updated to show a BIP21 payment request (still just the address).

**Comment by i5hi** [comment]
Also, the amount is only being allowed to be inputted in sats, not in BTC, even if chosen unit is BTC

**Comment by i5hi** [comment]
Fixed. Related issues addressed in https://github.com/SatoshiPortal/bullbitcoin-mobile/issues/9
