### ISSUE TITLE
"waiting for sync to complete" infinite load on receive Bitcoin page

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#104]
On the receiving Bitcoin page, I see a "waiting for sync to complete..." message instead of the wallet name. It has a loading icon with an infinite load. However, I think the sync should already be completed (I synced the wallet from homepage before). After about 60 seconds, still not complete. Seems to be a bug.

**Comment by i5hi** [comment]
Not able to reproduce this.
Please share a screen capture video.

Related to https://github.com/SatoshiPortal/bullbitcoin-mobile/issues/108
