### ISSUE TITLE
Wallet Sync Optimization

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#108]
After bdk sync, our native Wallet-Transactions-Addresses has a high time complexity to sync.

Every transaction is iterated over and each outAddr is attempted to be matched against addresses and updates made accordingly. 

This should happen in the background while the wallet continues to be usable.

We should also make the bdkWallet available before sync so that send and recieve can work on a pre-synced wallet. If the utxos used in a tx is valid, send should work completely even if sync is still in progress. Recieve will keep generating addresses from its lastUnused.

**Comment by i5hi** [comment]
Update: dart sync is not causing the delay, its bdk sync. So optimizing List operations is not a major priority.

**Comment by i5hi** [comment]
If wallet is not synced before sending coins, coins do not appear.

**Comment by mocodesmo** [comment]
@i5hi  utxo list was not being saved in storage
