### ISSUE TITLE
Change address must inherint label of outbound transaction label

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#11]
When making an outbound transaction, the change address utxo must inherit the label of the outbound transaction.

We know which utxo is the change utxo (supplied automatically by txbuilder) by the fact that it is not the recipient's address that was input by the user.

Currently not working as of 0.1.2

**Comment by i5hi** [comment]
Will be addressed in #40

**Comment by i5hi** [comment]
Fixed in 0.1.88
