### ISSUE TITLE
Watch-only wallets dont require backup

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#115]
Watch only wallets should now have a test backup section.

**Comment by mocodesmo** [comment]
@i5hi  this is unclear pls explain further

**Comment by i5hi** [comment]
```enum BBWalletType { newSeed, xpub, descriptors, words, coldcard }```

wallet-settings->backup,test-backup is only for newSeed, words - they have private keys in Seed that you need to have written down as a backup.

everything else is watchOnly so this wallet is not where backup happens, it would be usually the hardware signer where backup happens.
