### ISSUE TITLE
Transactions, Balance and Addresses not showing up on sync for recovered wallet

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#118]
Wallet syncs but transactiosn do not show up in the home page.

Addresses also do not show up apart from active change utxos. 

Balance shows up on homepage BUT does not show up in Wallet Details

**Comment by yshwanth** [comment]
Backup screen has no key error

**Comment by i5hi** [comment]
Partly fixed.
@mocodesmo current issue is related to getUtxos.

**Comment by i5hi** [comment]
Fixed. Thanks @mocodesmo
