### ISSUE TITLE
[Create Wallet Popup] Make each bullet point as checkboxes

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#129]
App version: v0.1.91

1. In Create wallet confirm popup, the bullet points looked like a checkbox. But they are not.
2. Making these as actual checkboxes would be good.
3. Increases the chances of the users actually reading those points.

![Create Wallet 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/bedff4f7-5652-43bb-a63b-96d1c17c9c7f)

**Comment by i5hi** [comment]
We discussed this and the verdict was to just show it as a list rather than force user to check the boxes.
