### ISSUE TITLE
[Create Wallet] Passphrase - Max length validation

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#131]
App version: v0.1.91

While creating a wallet, I pasted the entire contents of bitcoin wiki page.
The page accepted and created the wallet.

Can have a max length validation.

![Create Wallet 003](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/83bfdbcd-f91a-4763-b131-15075804c9f8)

**Comment by i5hi** [comment]
@mocodesmo for now you can set the limit as 32 characters
