### ISSUE TITLE
[Import wallet] Clear pubkey on back navigation

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#132]
App version: v0.1.91

1. Scan / paste some xpub, zpub.
2. Navigate back and enter Import wallet screen again.

Expected:
All fields should be in empty state.

Observed:
The xpub / zpub value is still there.

![Import Wallet 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/a0cf1163-819d-4c47-920f-b0e5cbf48bc5)

**Comment by i5hi** [comment]
Fixed.
