### ISSUE TITLE
[Import Wallet] Master public key: -1 on cancel scan

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#133]
App version: v0.1.91

1. Click on scan to open camera
2. Press cancel.
3. There will be -1 in the textfield.

Expected:
The value in the textfield, before opening the camera should be as it is.

![Import Wallet 002](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/1d182453-fb71-45fb-849d-874272be9463)

**Comment by i5hi** [comment]
@mocodesmo related to new QR library

**Comment by i5hi** [comment]
Even the old QR Library does this. 

Patched this by adding this:

```
  Future<(String?, Err?)> scan() async {
    try {
      final res = await FlutterBarcodeScanner.scanBarcode(
        '#ff6666',
        'Cancel',
        true,
        ScanMode.QR,
      );
      if (res == '-1')
        return (
          null,
          Err(
            'Did not scan anything',
          )
        );
      else
        return (res, null);
    } catch (e) {
      return (null, Err(e.toString()));
    }
  }
```

Seems hacky but makes sense, although its technically not an Err state.
