### ISSUE TITLE
[Import Wallet] NFC :: PlatformException message

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#134]
App version: v0.1.91

On mobile without NFC support, trying to activate NFC, shows the following message

"PlatformException(unavailable, NFC is not available for device, null null)"

Could be "NFC is not available for this device"

![Import Wallet 002](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/2893cb46-f781-46ab-8658-1e66309905eb)

**Comment by i5hi** [comment]
NFC is not supported yet. 

We should remove this option for now.

**Comment by i5hi** [comment]
Added coming soon notice on click.
