### ISSUE TITLE
[Import Wallet] Balance is shown incorrectly as 0

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#135]
App version: v0.1.91

1. I imported an mainnet wallet, using zpub.
2. In the scanning wallet screen, the Balance is shown as 0, though the First address is shown right

But after complete import, I am able to see all my txns and correct balance.

PS: When I tried importing the same wallet via 'Recover backup' (via seedphrase) option, the balances were shown right

![Import Wallet 003](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/01f12b63-8833-4cf8-8ea7-613cef65bd50)

**Comment by i5hi** [comment]
This could be an electrum issue. Try import the wallet and load it on the homepage. if sync is failing goto settings->electrum->click save on your node to resync.

It should work after that. This is a known bug and it is being addressed in #127

**Comment by saiy2k** [comment]
Tried couple of times now. But not able to reproduce.
