### ISSUE TITLE
[Recover backup] Clear words and passphrase on back navigation

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#137]
App version: v0.1.91

1. Type few words in the screen and also the passphrase.
2. Navigate back and enter the Recover backup screen again.

Expected:
All fields should be in empty state.

Observed:
The words and passphrase are still there.

![Recover backup - 12 words 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/534fcde6-f4ce-42a2-ac9e-631b23a09a69)

**Comment by i5hi** [comment]
Fixed. Thanks @saiy2k this was a good one!
