### ISSUE TITLE
[Recover backup] Error message not cleared between Import and Recovery

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#139]
App version: v0.1.91

1. Goto Import wallet, enter invalid xpub and click Import button.
2. 'Error creating wallets from xpub' will be shown.
3. Now navigate back to 'Recover backsup' screen and the same error is displayed below 'Recover' button

Have to just reset the error messages between screen transitions.

![Import Wallet 004](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/d3c84fff-60a8-4efb-b2d0-0a483464054d)
![Recover backup - 12 words 003](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/22ef78bc-39a6-4c17-a0d7-43a7016bd538)

**Comment by i5hi** [comment]
@mocodesmo this is a common pattern in other cubits as well.

We need to have a helper that clears cubit errorValues.

**Comment by i5hi** [comment]
@mocodesmo this is a common pattern in other cubits as well.

We need to have a helper that clears cubit errorValues.

Will be addressed in #119
