### ISSUE TITLE
Trigger wallet sync after import or recovery

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#14]
After importing a new wallet or recovering a wallet using a backup, automatically trigger a wallet sync.

**Comment by i5hi** [comment]
Another related issue is that when a new wallet is created and control returns to the homepage, the imported wallet data is not synced and going into wallet settings shows information about an older wallet.

Test this by importing a wallet and then going to settings and checking the backup  - the seed ill be from another wallet.

To fix this the user has to swipe to the older wallet and swipe back, only then the new wallet data is properly loaded.

@mocodesmo

**Comment by mocodesmo** [comment]
these are all fixed in the 0.1.6 release 
@i5hi pls verify

**Comment by i5hi** [comment]
You're right @mocodesmo 

This is fixed! Cheers!
