### ISSUE TITLE
[Test backup] Instruction label to be removed after successful backup test

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#141]
App version: v0.1.91

After successful backup test, The success message is shown, but the backup test instructions is still shown.

![Test backup 002](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/a738de9b-26d7-448c-b128-fcf998efef30)

**Comment by i5hi** [comment]
Fixed. Thanks @saiy2k
