### ISSUE TITLE
[Home/Testnet] Invalid txn list when home page is navigated to, after Sending a txn

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#144]
App version: v0.1.91

1. Have multiple wallets.
2. Send funds from 2nd or 3rd wallet.
3. After sending, you will be navigated to home screen.

where 1st wallet will be shown on top
and txn list of 2nd or 3rd wallet (the one you used for sending) is shown.

Tested this only with testnet wallets.

**Comment by i5hi** [comment]
Just had the same issue

**Comment by i5hi** [comment]
Fixed in 0.1.92
