### ISSUE TITLE
[Send / Receive] Need not show the list when there is only one wallet

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#145]
App version: v0.1.91

When there is only one wallet, clicking send/receive buttons need not show the wallet selection list.

![Receive 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/19eb1469-5ec5-46d0-9d66-21e8505951e9)

**Comment by i5hi** [comment]
Fixed on main.

**Comment by saiy2k** [comment]
Thanks. Very helpful :-)
