### ISSUE TITLE
[Home] Wallet card - Text overlap in CRC currency

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#146]
App version: v0.1.91

1. Select CRC in Settings :: Currency.
2. Have a 1m sats in the wallet.
3. The crc value overlaps with 'Spendable on-chain' label

![Home 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/2701675a-a320-4e21-91be-71f8e9e851fb)

**Comment by i5hi** [comment]
I think we should move the Wallet type 'Spendable Onchain' to the left column. @mocodesmo

**Comment by i5hi** [comment]
Moved all text items to the left
