### ISSUE TITLE
[Send Bitcoin] Camera cancel - Handle cancel

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#147]
App version: v0.1.91

1. Paste an address in address field.
2. Ppen camera and click cancel.
3. Now the address in the field is replaced by -1

Expected: It should be undisturbed. Previous address should be there.

![Send 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/94c164c4-2653-40ba-a426-ab96a797d3b7)

**Comment by i5hi** [comment]
Fixed on main.
