### ISSUE TITLE
[Send Bitcoin] Sending from mainnet to testnet wallet

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#148]
App version: v0.1.92

1. Create a receive address in testnet wallet
2. Switch to mainnet and goto send screen.
3. Paste the address and click 'Send'

Expected:
'Invalid address' should happen.

Observed:
The transaction is constructed and broadcasted.
It got listed in 'Pending txn' list for a while, before disappearning.

Same happens, when sending from testnet to mainnet wallet as well.

![Txn sent from mainnet wallet to testnet address](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/c16e9d77-9526-4f74-b91c-853ca46eaf1d)

**Comment by saiy2k** [comment]
A txn from mainnet utxo with 1st output address as testnet address, actually got mined and confirmed in a block!!

I assumed this will be rejected by miners and wouldn't get confirmed.

**Comment by i5hi** [comment]
I have added an explicit check now. 

In our test cases bdk always throws a address encoding error if the wrong network is used.

**Comment by i5hi** [comment]
Update:

We are using bdk.TxBuilder  (not bdkWallet) which does not care about the network being used. It finally adds a pubkey to the script and the output tx-hex is broadcasted using a broadcaster than does not check if output addresses are for testnet or mainnet either. 

So this was up to us to add that check and we now have it. 

I suspect that when the network gets this tx it just checks if the pubkey is valid, so the tx got accepted. mempool is displaying the corresponding address given the network. 

So you should be able to access this utxo by importing your testnet seed as a mainnet wallet. 

@saiy2k let us know if you were able to recover that utxo

**Comment by saiy2k** [comment]
Able to recover the UTXO via Blue wallet with custom derivation path m/84'/1'/0 in mainnet :-)

**Comment by i5hi** [comment]
Ahh, the derivation path!

On bull it would enforce path 0' for network.

Once we stabilize descriptor imports such recoveries should be possible.

**Comment by i5hi** [comment]
Closing this issue. 

Thanks again and sorry for the scares!
