### ISSUE TITLE
[Send Bitcoin] Amount field :: Sats <-> Btc conversion

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#149]
App version: v0.1.92

1. Set the unit as sats
2. Type 100 sats
3. Switch the unit to btc.

Expected:
The amount value to change to 0.0000100 btc

Observed:
The amount remains as 100 btc

![Send Bitcoin 002](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/6167f4af-a93f-479a-bc02-18c47a86d79c)

**Comment by i5hi** [comment]
Fixed on main.
