### ISSUE TITLE
Unsigned PSBT download button not working

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#15]
Downloading an unsigned PSBT doesn't work. Should be opening file directory so the user can save it directly onto a Cold Card virtual disk.

**Comment by BullishNode** [comment]
@mocodesmo the unsigned PSBT is saved automatically in the dowloads folder. It should prompt to decide where to save the file, because it will usually be either a virtual disk (USB) or an SD card, not downloads folder.

**Comment by i5hi** [comment]
This has been fixed since 0.1.8
