### ISSUE TITLE
[Send Bitcoin] Address field validation message could by user friendly

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#150]
App version: v0.1.92

The error message could be
'Address field is required', rather than 'base58 address encoding error'

![Send Bitcoin 003](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/f8dabadd-26d9-47e8-ba01-115058883dcd)

**Comment by i5hi** [comment]
Closing this as it will all be addressed in #35 

We just got typed errors from bdk so we will be updating it across the code base.
