### ISSUE TITLE
[Send Bitcoin - Bump fee] Panic exception

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#151]
App version: v0.1.92
In Testnet

1. Make a transaction
2. Goto Bump fee of that txn page
3. Set insanely high feerate, like 10000
4. Click 'Send Txn'

Expected:
There should be a max validation for fee rate field, which doesnt allow txn sending with high rates like this

Observed:
Getting 'Panic Exception'
After which can't even send a new regular transaction between other wallets in testnet.
PS: Restarting the app fixes the issue. Can then send any txns

![Bump fee 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/e63da937-588c-4951-bc57-8376001e5890)
![Send Bitcoin 004](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/ca57c3bd-ec70-46bf-97cd-f515502fce69)

**Comment by i5hi** [comment]
For now, if you see Panic Exception its most of the time an Electrum error. You have to goto settings and resave electrum settings.

Related to #127

**Comment by i5hi** [comment]
Added max fee rate validation.
