### ISSUE TITLE
[Send Bitcoin] Amount is bip21 URI is not parsed

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#152]
App version: v0.1.92

1. Create a bip21 URI (bitcoin:tb1q9cys36fmxu6jc8vaf4fx8h6a6ffr8zgrezpjj9?amount=0.00025000&label=For fruits)
2. Paste it in address field in 'Send bitcoin' screen.
3. Address, Label fields are rightly populated, but amount field remains empty

Expected: Amount field populated with value from the URI and Send button to be enabled
Observed: Amount field is empty and Send is disabled.

![Receive bitcoin 002](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/60f149b8-3a8e-467b-8bdf-fdb7a0e77af5)
![Send bitcoin 005](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/aebb8154-b88c-426d-8004-5fe190353da8)

**Comment by i5hi** [comment]
Patched on main.
