### ISSUE TITLE
[Send Bitcoin] Back navigation issue

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#153]
App version: v0.1.92

1. Go inside a wallet, click send/receive.
2. Now click the back button in screen.

Expected: Should navigate back to wallet screen
Observed: Navigated to Send/Receive wallet list

![Receive bitcoin 004](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/6aa2aca9-6bb7-4f10-a1a6-a16c9378e367)
![Receive bitcoin 005](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/764704bf-8289-482a-bf65-07abea9b3b31)

**Comment by i5hi** [comment]
Patched on main.
