### ISSUE TITLE
[Send Bitcoin :: Coin selection] Error of 'UTXOs counting to less sats than send amount' is not explicit

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#154]
App version: v0.1.92

1. Set send amount to 100,000
2. Select UTXO whose value is less than 100,000
3. In send screen, Send button is disabled, which is right.

But not obvious, why it's disabled.

2 solutions:
 1. Below `Selected [x] addresses`, Message like, 'Selected UTXOs are not enough to send [send] amount' could be shown above disabled 'send button`.
 2. This validation can happen in 'Coin selection' screen and 'Send' button disabled in that screen, till enough UTXOs are selected." with same message as above.

![Send bitcoin 006](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/4b291f97-b13e-4ee3-a5dc-538e5841f447)
![Send bitcoin 007](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/999d1115-0732-4ac1-b969-6af0d2e2e6b9)

**Comment by i5hi** [comment]
@mocodesmo 

Using the above screenshot as an example, we should do the following check: 

- Send amount (S) = 50,000 sats
- Utxos value (U) = 24,859 sats
- Utxos selected (Un) = 1 selected
- Fee Rate (F) = 1 sat/byte
- Size of 1 Utxo (Us) = 140 bytes (This is a constant we assume for all transaction outputs)

The calculation we need to do is:

IF:

`U - ( S + (F*Us*Un)  ) > 0`

ALLOW SEND.

Else: 

DISABLE SEND w/NOTICE: `Selected Utxos Does not cover Transaction Amount & Fees`

**Comment by i5hi** [comment]
Fixed on main.
