### ISSUE TITLE
[Bump Fees Popup] Can merge 'Build Transaction and Send Transaction' into a single 'Bump Transaction'?

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#155]
App version: v0.1.92

Can merge 'Build Transaction and Send Transaction' into a single 'Bump Transaction'?

**Comment by i5hi** [comment]
Need more details...

**Comment by saiy2k** [comment]
These 2 buttons could be a single button / single action:

![Bump 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/1c1fcb50-0045-4555-82b2-84c513064746)
![Bump 002](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/275fdd14-93ad-41bc-88bd-fb1604f7758b)

**Comment by i5hi** [comment]
Done.
