### ISSUE TITLE
[Receive bitcoin :: Amount request] Amount request is not populated when edit

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#159]
App version: v0.1.92

1. Click 'Request a payment'
2. Enter some amount, label and click save.
3. Now click on requested amount again to open the popup. (Could have a edit button)

Expected
The amount and label that I entered previously be populated in the form.

Observed
The fields are empty.

![Receive Bitcoin 006](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/1e460ad5-c9e0-48de-849e-61ee15237004)
![Receive Bitcoin 007](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/69ace629-ad68-4ef8-8405-80c885fc0232)

**Comment by i5hi** [comment]
Edit button has been added.
