### ISSUE TITLE
Recipient address = Sender change

### ISSUE THREAD

**Issue by JuanOfTheNorth** [SatoshiPortal/bullbitcoin-mobile#16]
Clicking on a received transaction, <Recipient bitcoin address> shows sender's change address.

v 0.1.2

Android

**Comment by BullishNode** [comment]
Thanks for the report.

Cc @mocodesmo

**Comment by i5hi** [comment]
Thanks @JuanOfTheNorth 

Tested and fixed on main branch. Will be available on the next release - 0.1.7.
