### ISSUE TITLE
[Wallet page] Txns not refreshing

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#160]
App version: v0.1.92

Should add 'swipe down to refresh' in this page, as in Home page.

![Wallet 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/45b179df-25be-47b2-87fd-b3e6b8609bbd)

**Comment by i5hi** [comment]
Updated on main.
