### ISSUE TITLE
[Wallet page] Balance is including frozen UTXOs

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#161]
App version: v0.1.92

Balance shouldn't include frozen UTXOs, as they can't be spent.

Steps:
1. Goto Wallet -> Settings -> Address
2. Freeze some UTXO.
3. Goto wallet page and see the balance

Expected:
It should show balances from unfrozen UTXOs

Observed:
It shows balances from all UTXOs

PS: Samourai wallet works this way.

**Comment by i5hi** [comment]
This is expected behaviour but the confusion is fair.

We can address this by adding a notice about frozen balance if any on the send page.

**Comment by i5hi** [comment]
Final: 

- Let all balances on Home include Frozen UTXOS. (No change to how it already is)
 
- On send page, show balance EXCLUDING frozen utxos and right under the balance show `Frozen Balance`.

**Comment by i5hi** [comment]
Fixed on main.
