### ISSUE TITLE
[Receive bitcoin] Address label is not visible anywhere

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#165]
App version: v0.1.92

1. Goto Receive bitcoin screen
2. Set address label
3. Send sats to that address

Expected:
1. Address label to be shown in txn page next to Recipient bitcoin address
2. Wallet -> Settings -> Addresses. Respective address to display the given address label.
3. Wallet -> Settings -> Addresses -> Tap on that address. The address label to be displayed in the address popup.

Observed:
1. The label is not seen anywhere

Note: Same behavior when you do 'Edit label' in Address popup, save the label, go back to home and check in wallet again.

![Receive 005](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/963f1b32-d442-4f6f-950f-84854312d5ec)

![Receive 006](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/842c1063-23a4-46d5-9981-5aa623386b5b)
![Receive 007](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/f95383fb-03d6-4e88-abd2-f73ee2787207)
![Receive 008](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/12492386-6761-4f3c-89be-1dae9b342ebf)

**Comment by i5hi** [comment]
Fixed on main. Address label was being overwritten by empty tx label.
