### ISSUE TITLE
Txn Label - Auto override

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#166]
App version: v0.1.92

There are 2 wallets: Pikachu and Vegeta.

1. Create a receive address in Vegeta. Let's call it VAddr1
2. Send sats from Pikachu to VAddr1 and label the Txn 'TxPSend1'
3. In Vegeta, set the txn label as 'TxVRcv1'

Wallets looks as below:
![Label 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/d5a285d2-7cfa-4982-bff2-211dbab6c3b6)
![Label 002](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/510bec37-8e12-49f8-8ff3-7cea6a1664ad)

4. NowSend sats again from Pikachu to VAddr1 and label the Txn 'TxPSend2'
![Label 003](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/df77c24d-c343-4bae-9864-02fa6a6713b7)

5. In Vegeta, set the txn label as 'TxVRcv2'
5.1 Before labeling
![Label 004](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/73de1b97-0e96-44f7-a835-414290ea9aa9)

5.2 Immediately after labeling
![Label 005](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/d674efa9-63a6-4b97-97bc-19afa2746da0)

5.3 After a refresh
![Label 006](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/55a821d9-eaad-4628-82a6-c6a08061a012)

The label 'TxVRcv2' overrides the label 'TxVRcv1' of the first transaction.

**Comment by i5hi** [comment]
Current behaviour of labeling:

Tx will inherit the address label. (we should make it so that if tx label is set, do not inherit from the address)

If address label is not set, it will inherit tx label, other wise changes in tx label will not affect address label.

**Comment by i5hi** [comment]
Needs review. We have made some fixes to label inheritance.
