### ISSUE TITLE
[Wallet :: Settings :: Address] Change address could show some first address

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#167]
App version: v0.1.92

When there is no change address, can show the first address.

My primary intent is aesthetics. Right now the empty popup looks visually blunt.

![Change 01](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/b8a01801-a922-4910-86af-4dd032dbd436)

Blue wallet as reference.
![Change 02](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/e562453f-3f40-4f8c-a693-d4686976306c)

**Comment by i5hi** [comment]
Agreed. Right now we are also unable to get the index of change. To get change addresses out of bdkFlutter requires us also loading a changeWallet. We attempted this at one stage but it was difficult to test without unit test support from bdkFlutter. 

We will revist this and find a solution. 

For now, the following message should be fine:

`No change addresses generated yet...`

**Comment by i5hi** [comment]
Fixed on main.
