### ISSUE TITLE
[Send Bitcoin] Send entire balance UI

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#168]
App version: v0.1.92

When 'Send entire balance' is selected, amount field is not shown.

Suggestions:
1. Amount field shown in disabled state with full sats value.
2. Amount field replaced with a label saying something like 'MAX ([all sats])'

![Send all 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/3f1dc783-81c9-45a3-a90c-d0bd1145741d)

It's unclear from this screen, that 'Send entire balance' is selected:
![Send all 002](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/b82acbe6-feb1-4279-a250-863b7b5eefad)

**Comment by i5hi** [comment]
We cannot get the exact amount until we build the tx in the next page, so on this page we can just show 

`MAX`

**Comment by i5hi** [comment]
Fixed on main.
