### ISSUE TITLE
[Settings :: Default fee] Should set some max limit for the custom field

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#169]
App version: v0.1.92

1. Goto Settings :: Default fee
2. Set custom fee as 20000
3. Now send a txn. All your sats will be consumed by the fee.

Expected:
Default fee custom field should have a max limit validation rule.

Observed:
It's accepting any huge values now.

![Default fee 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/5106283e-4380-4c48-8153-aff6301254de)

**Comment by i5hi** [comment]
Nice one!

**Comment by i5hi** [comment]
I think we can safely set the max limit to 50 sats/byte for now. Since it is default, user can always make it higher.

**Comment by BullishNode** [comment]
Can we make max limit something like 2x the priority fee?

**Comment by i5hi** [comment]
Limits now enforced with new network_fee cubit.

Minimum is low fee and Max is priority * 2
