### ISSUE TITLE
"tap to test backup" should open in backup view

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#17]
The "tap to test backup" link on the homepage should open to the backup view, instead of wallet settings.

**Comment by i5hi** [comment]
@mocodesmo will need your help on this. We dont have a router to go directly to the test page. Not sure how to make this work. 

Route to settings and simulate a button press or change the cubit state to redirect to the test backup page?

**Comment by mocodesmo** [comment]
fixed on main
