### ISSUE TITLE
[Settings :: Default fee] Fee rate selection shoudn't save without pressing 'Done' button

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#170]
App version: v0.1.92

1. Switch to a different fee box, than current
2. Tap h/w back button to close the popup.

Expected:
The fee rate change shouldn't be saved, withough pressing 'Done' button.

Observed:
The change is saved.

![Default fee 002](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/2d07da5c-58a8-4de2-8f73-05aa396663f1)

**Comment by i5hi** [comment]
Agreed.

**Comment by i5hi** [comment]
Fixed.
