### ISSUE TITLE
[General] Better error handling UI

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#171]
App version: v0.1.92

Right now, error messages are shown above / below, action buttons. Could be shown in a standard alert dialog.

![Error 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/2e8880f2-32c8-4165-9e5e-77b179b39f8e)

**Comment by i5hi** [comment]
Closing in favour of #174
