### ISSUE TITLE
[Wallet :: Settings] Wallet name is shown as placeholder

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#172]
App version: v0.1.92

Wallet name is now shown as a placeholder, rather than actual field value.

![Wallet Settings 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/8348804d-f0e5-4b23-9a03-a6402502ca65)

**Comment by i5hi** [comment]
This is based on the Figma spec. Closing this for now.

**Comment by BullishNode** [comment]
Maybe replace input field by list item with an edit button?
