### ISSUE TITLE
[Settings::Fees] Buggy input field

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#177]
Settings -> Default Fee related isssues.

**Comment by i5hi** [comment]
- [ ] Input field should be visible while typing

- [ ] When typing numbers

**Comment by saiy2k** [comment]
Previously mentioned issues are fixed.
But the auto-correction seems little annoying.

1. When I type 500
2. It reset to 2
3. Now I decide to go with 20 and type a 0
4. It removed the 0 and resets to 2
5. Typing 0 again, sets the field to 20

**Suggestion**
Let the user type whatever number they want, even 500000. But just show validation error and disable the Done button.

https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/8441e56d-f8f7-4b85-a4be-0c6e8394cbc2

**Comment by mocodesmo** [comment]
@i5hi  @saiy2k i am not seeing this behaviour anymore 
pls recheck with latest release and close if fixed

**Comment by i5hi** [comment]
all good now!

**Comment by saiy2k** [comment]
Hi.
Just retesting this. Above issues are fixed now.

But 1 small thing still. Setting anything above 50, saves the value as null

![F001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/c3ec3b90-3437-4042-bc5a-e7e595a4b400)
![F002](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/cbb8ecd8-c3a3-4d17-ab03-7ca90337221a)
![F003](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/8eeb3bae-c385-4862-876f-255431e058c8)

**Comment by mocodesmo** [comment]
@saiy2k  can't replicate the null error
do u think it could be caused by something different ?

**Comment by i5hi** [comment]
Fixed on main.
