### ISSUE TITLE
[Settings] CAD is not visible in currency list (Not easily reproducible)

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#178]
App version: 0.1.94

I just randomly navigation between home, settings, wallet pages. Each time opening the currencly list select in settings page.
INR is selected.

Sometimes, CAD is not shown. Then any amount of re-navigating is not bringing it back.
Closing the app and re-opening fixes the issue.

![Currency 001](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/6256b8d0-4645-40f3-b36a-12627faf3dbc)

**Comment by yshwanth** [comment]
version 0.1.94
There is no CAD option visible.

**Comment by i5hi** [comment]
Fixed in 0.1.96
