### ISSUE TITLE
[Wallet :: Settings] Mismatch for (possibly a recovered) wallet

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#179]
App version: 0.1.94

1. Have a wallet 'Pikachu'
2. Recover a wallet by entering seedphrase and call it 'Vegeta'

1. Now open 'Pikachu' wallet and goto settings. It works as expected.
2. Now open 'Vegeta' wallet and goto settings screen.

Expected:
1. To see settings page of 'Vegeta' wallet.

Observed:
Settings page of 'Pikachu' wallet is shown.

Video recording of the issue, is posted in slack.

**Comment by saiy2k** [comment]
Also happens, when you delete a wallet and goto Settings page of remaining wallets.

Posted video in slack.

**Comment by i5hi** [comment]
Fixed in 0.1.95
