### ISSUE TITLE
Default wallet naming conventions

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#18]
We should avoid using the fingerprint as wallet label as much as possible because it is a confusing UX.

Default wallet name = Bull Wallet
Default testnet wallet name = Bull Wallet Testnet
Coldcard import = Coldcard
Other imported wallets = Imported Wallet 

New wallets and recovered wallets can keep the wallet fingerprint as wallet name for now.

**Comment by i5hi** [comment]
Fixed.
