### ISSUE TITLE
[Send Txn] Cannot bump a txn twice

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#182]
App version: v0.1.95-01/Testnet

1. Send a txn.
2. Bump it once.
3. Open txn page.

Expected:
`Bump fee` button to be visible and working.

Observed:
`Bump fee` button is not visible.

**Comment by saiy2k** [comment]
Addional info:
- When the txn is first broadcasted, RBF is enabled.
- But when it's bumped, RBF is disabled (Not by user's choice)

<img width="1012" alt="Screenshot 2023-11-07 at 2 08 32 PM" src="https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/a10c72f7-5896-4dbc-9143-02d303309310">

<img width="1110" alt="Screenshot 2023-11-07 at 2 08 38 PM" src="https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/cfdadedb-e033-4822-8c8a-7e1527606a51">

**Comment by i5hi** [comment]
fixed on main
