### ISSUE TITLE
[Fiat currency selection] Not consistent across the app

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#184]
App version: v0.1.95/Mainnet

1. CAD was the default currency in Settings.
2. I change it to USD. It's reflected in Send, Receive -> Request a payment screens. 
3. But not in home page wallet card, wallet page top, network fee popup.
4. Same happens with CRC, INR.

End of the video:

1. I close the app and re-open it.
2. Navigate to Settings page.
3. My currency selection got auto-updated to USD from my selection of INR. (Without me doing anything)
4. And sometimes, not all 4 currencies are shown. Just 3 and rarely just 1(Screenshot)

https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/cb8b07b8-6a0a-411e-8038-363e940f9ebd

![Screenshot_2023-11-07-19-54-33-988_com bullbitcoin mobile](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/a3f7b6e3-d546-4e02-8212-819ab935e3ef)

**Comment by saiy2k** [comment]
Fiat update is now fixed in
1. Home page wallet card,
2. Wallet page top
Also, the Settings :: Currency list shows all fiats currencies now.

Still open:
1. Network fee popup is still CAD always.
2. On re-start, for few seconds it's shows my selected fiat in home page and then it resets to CAD.

**Comment by i5hi** [comment]
Fixed in 0.1.96
