### ISSUE TITLE
[Fiat price/Testnet] Shown in Send, receive, fee rate screens

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#185]
App version: v0.1.95/Testnet

Should be 0.

![Screenshot_2023-11-07-19-38-25-833_com bullbitcoin mobile](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/8c8eff5f-aead-4c1b-8d7e-03a021880a5a)
![Screenshot_2023-11-07-19-37-52-421_com bullbitcoin mobile](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/aab6bf18-fef9-4911-96d0-5e86e5e54c87)
![Screenshot_2023-11-07-19-37-39-177_com bullbitcoin mobile](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/815aae64-6e49-4c40-a992-dee75632e329)

**Comment by i5hi** [comment]
Fixed on main
