### ISSUE TITLE
Typo in Bull Bitcoin Wallet (No passphrase) label type

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#19]
There is a typo in the wallet type for Bull Bitcoin Wallet (no passphrase).

Currently says _Bull Bitcoin Wallet (No passphase)_
Should be _Bull Bitcoin Wallet (no passphrase)_

**Comment by i5hi** [comment]
Make it all PascalCase? 


This is what it currently is for all wallets:

```dart
String getWalletTypeString() {
    String str = '';

    switch (type) {
      case BBWalletType.newSeed:
        str = 'Bull Bitcoin Wallet';
        if (hasPassphrase())
          str += '\n(Passphase Protected)';
        else
          str += '\n(No passphase)';

      case BBWalletType.xpub:
        str = 'Imported Xpub';
      case BBWalletType.words:
        str = 'Imported Mnemonics';
        if (hasPassphrase())
          str += '\n(Passphase Protected)';
        else
          str += '\n(No Passphase)';
      case BBWalletType.coldcard:
        str = 'Imported Coldcard';

      case BBWalletType.descriptors:
        str = 'Imported Descriptors';
    }
```

**Comment by i5hi** [comment]
> Make it all PascalCase?
> 
> This is what it currently is for all wallets:
> 
> ```dart
> String getWalletTypeString() {
>     String str = '';
> 
>     switch (type) {
>       case BBWalletType.newSeed:
>         str = 'Bull Bitcoin Wallet';
>         if (hasPassphrase())
>           str += '\n(Passphase Protected)';
>         else
>           str += '\n(No Passphase)';
> 
>       case BBWalletType.xpub:
>         str = 'Imported Xpub';
>       case BBWalletType.words:
>         str = 'Imported Mnemonics';
>         if (hasPassphrase())
>           str += '\n(Passphase Protected)';
>         else
>           str += '\n(No Passphase)';
>       case BBWalletType.coldcard:
>         str = 'Imported Coldcard';
> 
>       case BBWalletType.descriptors:
>         str = 'Imported Descriptors';
>     }
> ```

Fixed `Passphase` spelling to `Passphrase` xP
