### ISSUE TITLE
Add back .APK file in Releases.

### ISSUE THREAD

**Issue by BonHodl** [SatoshiPortal/bullbitcoin-mobile#190]
Please consider including .APK's again in the releases section. This allows users to directly install updates from GitHub or via Obtanium. Thank you.

**Comment by BullishNode** [comment]
.apk is still available in the zip file in the releases

**Comment by BonHodl** [comment]
> .apk is still available in the zip file in the releases

Yes this is nice and how I originally installed the app, though the zip. It is a bit of a pain to follow updates and update the app itself this way on mobile though. There are a growing number of us that are going around app stores and trying to get software straight from the developers. .apk direct from releases page is a great way to do this. Obtanium is an even greater way as you can follow repos directly, get notified of updates and install releases directly from the binaries if they are available. Just a thought, it's nice to avoid google play, appstore gatekeepers when possible.

**Comment by i5hi** [comment]
100% 

We are still in the process of making reproducible builds, even for devs. Until we have this, installing the apk from the release is actually more trusted. 

Once we have reproducibility for devs, we would have to always check if the release on Play matches what we have published on Github. Surely Play is not tampering with the release but the only way we can guarantee that is by having a check for reproducibility. 

Eventually the goal is for even users to be able to reproduce the build themselves for maximum minimization of trust.

**Comment by i5hi** [comment]
@BonHodl does obtainum require us to release the apk outside a zip file or the zip okay?

**Comment by i5hi** [comment]
i noticed this:
https://github.com/ImranR98/Obtainium/discussions/884

Seems like it is not supported.

We recently updated to the zip format because we also publish .aab format and each with accompanying signatures, so zip seemed like a good way to package everything. We also internally pass around a zip on apps like Signal which do not allow passing around a .apk file.

If this doesnt work with Obtainium, we can include the apk separately from next release onwards.

**Comment by BonHodl** [comment]
> i noticed this: [ImranR98/Obtainium#884](https://github.com/ImranR98/Obtainium/discussions/884)
> 
> Seems like it is not supported.
> 
> We recently updated to the zip format because we also publish .aab format and each with accompanying signatures, so zip seemed like a good way to package everything. We also internally pass around a zip on apps like Signal which do not allow passing around a .apk file.
> 
> If this doesnt work with Obtainium, we can include the apk separately from next release onwards.

Obtanium needs an .apk in the releases to work. Thank you very much, including the apk would be much appreciated. I have the signal APK in obtanium as well and it works 👍

**Comment by i5hi** [comment]
Will start doing this from next release onwards!

Thanks for the issue!

**Comment by i5hi** [comment]
https://github.com/SatoshiPortal/bullbitcoin-mobile/releases/tag/v0.1.97

New asset upload format for releases.

Does this work ?

**Comment by BonHodl** [comment]
> https://github.com/SatoshiPortal/bullbitcoin-mobile/releases/tag/v0.1.97
> 
> New asset upload format for releases.
> 
> Does this work ?

It worked! I updated a couple days ago. This is a great option to avoid app store gatekeepers. Thank you.

**Comment by i5hi** [comment]
Thanks for the suggestion!
