### ISSUE TITLE
[Test backup] On wrong order selection, error is shown and quickly cleared

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#197]
App version: 0.1.97

Select invalid order of words

Expected:
Error saying 'Selection is invalid'

Observed:
Error is shown. But within a second, it's getting reset along with word order.

https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/0fed509f-b78d-4c3a-bd4e-7ad86bc2dcbe

**Comment by i5hi** [comment]
I think the new error module implemented here should fix this.

The words should reset after the error dialog is closed.
