### ISSUE TITLE
Bug when creating unsigned PSBTs

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#20]
When creating an unsigned PSBT from a watch-only wallet, the tx builder seems to be trying to add the recipient address as one of the inputs. The end result is that a Coldcard is not able to sign the unsigned PSBT with the error message "Signing failed late. Path (m/84'/0'/0'/0/3) let to the wrong pubkey for input#0). I used a brand new coldcard wallet for this so the path should probably have been (m/84'/0'/0'/0/0). Not exactly sure what is going on, but definitely a bug here in the way the wallet is crafting the unsigned transaction.

**Comment by i5hi** [comment]
This can be closed.

**Comment by i5hi** [comment]
Broadcast in the psbt flow is still buggy, made a new issue for this which should be resolved by eod.

Following that please review the entire psbt flow.

**Comment by i5hi** [comment]
Fixed in 0.1.5
