### ISSUE TITLE
[Fiat currency] Not updated in Fee rate box and getting reset to CAD on app re-start

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#202]
App version: v0.1.97/Mainnet (001325b147e0b5a29debbbc1207ae99e5b08ed03)

- [x] Network fee popup is CAD always.
- [x] On re-start, for few seconds it's shows my selected fiat in home page (/wallets) and then it resets to CAD.

**Comment by mocodesmo** [comment]
@saiy2k @i5hi fixed last 
works on my side

**Comment by saiy2k** [comment]
Yes. Second point is fixed now.

**Comment by i5hi** [comment]
First also fixed.
