### ISSUE TITLE
[Broadcast] Stuck with Panic exception

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#204]
App version: v0.1.97/Mainnet (001325b147e0b5a29debbbc1207ae99e5b08ed03)

1. Decode successfully happens.
2. Always gets stuck on Broadcast.

On Inspect, it's always PanicException. Tried
1. Restarted the app
2. Switched between BB and Blockstream electrum servers.

Apart from getting `PanicException`, another error while trying to get `message` property of the exception.

https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/283de82f-cf35-46e5-af2a-5ef61dca6b6f

<img width="909" alt="Screenshot 2023-11-16 at 2 09 24 PM" src="https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/93fb9985-37e0-42bd-b6df-3e8e1b66061e">

**Comment by mocodesmo** [comment]
fix on main yesterday 
@saiy2k pls retry

**Comment by saiy2k** [comment]
Yes. It's working good now. Closing this
