### ISSUE TITLE
Don't remove the test backup function in wallet settings when backup in tested

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#21]
In version 0.1.3 the test backup function was removed from wallet settings when the test has been completed. 

We can use the following design:

- if backup is not tested, put "Not tested" label in list element in red (C50909)
- if backup is tested, put "Tested" label in list element in green (12BD23)

**Logic:** a user may want to test the backup multiple times, not just one time.

**Comment by BullishNode** [comment]
![image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/75800272/c772f130-dd1b-40dd-9a08-06f8d3d1355c)

**Comment by BullishNode** [comment]
Actually, the test backup feature is still available in the backup page.

**Comment by i5hi** [comment]
Can be closed.
