### ISSUE TITLE
[Send Screen] Paste from clipboard

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#213]
Feature request

Send screen could have an option to paste address from clipboard.

How this is handled in (for reference):

Green
![IMG_6061](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/63173038-f6a8-438f-a661-94a0efa6c791)

Phoenix
![IMG_6058](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/89398cd8-7752-445c-a61b-73a4a7cd4e86)

Blue wallet
![IMG_6059](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/6131301b-a116-4901-b450-a4f855c30f7a)

Muun wallet
![IMG_6060](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/06324db0-01d4-418e-90fd-9611e6ff9315)

**Comment by yshwanth** [comment]
For import xpub wallet textbox too.![Screenshot_20231125-221258.png](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/42468133/60565180-c40e-4602-87e7-366d96043258)

**Comment by mocodesmo** [comment]
@i5hi @BullishNode  pls advise on ui and placement of paste button

**Comment by yshwanth** [comment]
Green wallet icon suits better

**Comment by i5hi** [comment]
I think the way Green does it is neat.

Its similar to how we have the `QR` button in `Import-Xpub` & `Send-Amount` - we can just add a `Clipboard` Icon

**Comment by BullishNode** [comment]
Even if its a little invasive, it creates a really smooth UX. I like.

**Comment by mocodesmo** [comment]
the paste button has now been added address field (send page) and xpub field (import page) .
next release will have these.
