### ISSUE TITLE
[Electrum :: Advanced] Hard to edit

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#214]
Stop gap has a default value of 20. I wanted to set it to 5.

1. Click the field and enter backspace once.
2. 0 is deleted and 2 is shown.
3. Now press backspace again.

Expected:
2 to be deleted. So I can enter the value fresh.

Observed:
0 appers, making the field value as 20.

Similar behaviour happens with the other fields, retry and timeout.

https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/6e44c380-8393-4001-8b68-6a09afcd6a2e

**Comment by mocodesmo** [comment]
fixed on main 
pls retest. @saiy2k
