### ISSUE TITLE
Change PIN in Settings is erroring 

### ISSUE THREAD

**Issue by shreyanjoshi** [SatoshiPortal/bullbitcoin-mobile#218]
There is no option to set PIN, and when I go to Settings -> Change PIN, it is not allowing me to save PIN. Please fix the issue. 
I also think set PIN should be by default when user downloads the app.

**Comment by saiy2k** [comment]
Hi. Can you please copy the app version, in which this issue is happening?

**Comment by mocodesmo** [comment]
closing due to non response from @shreyanjoshi and steps to replicate this issue do not cause mentioned 'erroring'
