### ISSUE TITLE
Selecting a utxo  during coin selection changes the send amount (bug)

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#22]
When using the coin selection option, selecting a UTXO will change the send amount (amount required).

The send amount should not change when doing coin selection *unless the "send full balance" option is also activated*.

If the "send full balance" option is activated at the same time as coins are selected, the amount sent will be the amount of the coins selected. But if the "send full balance" option is not selected, the amount sent is the amount that is input by the user, we do not choose the amount to send, the user chooses it.

**Comment by i5hi** [comment]
Fixed.
