### ISSUE TITLE
[Receive/Send screen] currency field popup should be round rather sharp edges

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#221]
App version : 0.1.98.-1.1

Receive bitcoin ( Request a payment )

Suggestion : Choosing amount filed settings should be in each wallet settings rather on receive amount page

![req-payment-error](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/42468133/b6149725-c6b7-4e4b-bc5c-df15bed6728c)

**Comment by mocodesmo** [comment]
this issue is very unclear 
please clarify

**Comment by yshwanth** [comment]
Choose amount field setting should be similar to kind of App themes UI. Its more clean and neat

**Comment by mocodesmo** [comment]
@i5hi @BullishNode  thoughts? 
Should we go with popup + radio buttons instead of the dropdown ?

**Comment by BullishNode** [comment]
Can you post screenshots?

**Comment by BullishNode** [comment]
This is what you mean? ![Screenshot_20231214-094938.png](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/75800272/eca56918-5864-4f3d-b050-081c88a54be6)

**Comment by yshwanth** [comment]
![signal-2024-02-02-10-26-14-465.png](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/42468133/fb545e10-c2b3-40cd-9a69-2c1731adef29)

Currency field should on bottom and should take bottom sheet overlap similar to App themes @mocodesmo @BullishNode @i5hi
