### ISSUE TITLE
[Wallet details ]Text Font should be small and concise rather bold 

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#222]
App version:0.1.98-1.1

Wallet Details 
 1. Text font (wallet details) content font should be small and concise rather bold 
 2. Don't make it Bold/thick, its odd looking wallet details when rest screen are not bold font

**Comment by mocodesmo** [comment]
fixed on main

**Comment by yshwanth** [comment]
Tested, looks good.
