### ISSUE TITLE
'TextScaler' Error Still Not Resolved Yet

### ISSUE THREAD

**Issue by QBlockQ** [SatoshiPortal/bullbitcoin-mobile#223]
Please don't close the issue till it is resolved.  The error is still there even with flutter clean the'TextScaler' and debugging must be done to check and verify the class definition, typos, update dependencies, check for compatibility issues, review the Error Logs.  For further information, please let's know.

**Comment by mocodesmo** [comment]
The Textscaler api was updated in a recent flutter version. 

Please provide the flutter version you are running

**Comment by QBlockQ** [comment]
Flutter 3.13.8 

I just run again and same error:

Error (Xcode): lib/main.dart:94:41: Error: The getter
'TextScaler' isn't defined for the class
'BullBitcoinWalletApp'.

**Comment by mocodesmo** [comment]
https://docs.flutter.dev/release/breaking-changes/deprecate-textscalefactor

**Comment by QBlockQ** [comment]
What's holding your hands to do it and update your Flutter code with TextScaler!
