### ISSUE TITLE
[Paste Text Field]Address Textbox of Send page after Using pasting button only delete one field

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#225]
App version:0.1.98-1.1

Paste button - Address Textbox of Send page after Using pasting button only delete one field instead of deleting long press entirely.

Description: Paste button is working good but when I do backspace on field ,its only deleting one space and exiting

**Comment by mocodesmo** [comment]
fixed on main 
this was initially done because long pressing and pasting directly into the textfield would keep the keyboard onscreen

**Comment by yshwanth** [comment]
Done testing the backspace fields, working as expected. Resolved
