### ISSUE TITLE
[Send] Coins selected number keeps on increasing

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#226]
App version: 0.1.98-1.1

Description: Coin selected issue- The coin selected number keeps on increasing irrespective of no of utxos

Reference- ...

**Comment by mocodesmo** [comment]
@i5hi fixed on main

**Comment by i5hi** [comment]
@yshwanth please confirm that this issue is resolved after testing?

**Comment by yshwanth** [comment]
Its resolved👍

**Comment by i5hi** [comment]
Cheers!
