### ISSUE TITLE
[Electrum] Connecting to local Umbrel without SSL

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#229]
App version: 0.1.98-1.1

Description: When connected to local electrum server without SSL (Umbrel), I found strange that wallet sync happening without SSL.
- SSL://umbrel.local :50001 works fine and sync wallet without no issues
- umbrel.local:50001 works fine and sync wallet but errored range of 0-1 
![Ele-range](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/42468133/bef0036f-f807-4d3c-83e6-75710f7bcde8)

**Comment by i5hi** [comment]
Try with url prefix tcp://
