### ISSUE TITLE
Creating a duplicate default testnet wallet and removing main net default wallet when I look into transaction on mempool

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#23]
![Screenshot_20230705-142419.png](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/42468133/023fbe23-987a-46f1-bd20-2bd8c637c7b8)

![Screenshot_20230705-142614.png](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/42468133/028fa646-9788-4836-a588-cbc4dbf6bfd7)

**Comment by mocodesmo** [comment]
@yshwanth  can u please add more details on what the bug is and how you encountered it ?

**Comment by yshwanth** [comment]
When I am on Transaction page, on click of Tx I'd or address ,it goes mempool space. After clicking back from mempool , the above bug arises

![Screenshot_20230705-165609.png](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/42468133/0e3b2144-2046-4efd-ab5b-b9a457303834)

**Comment by i5hi** [comment]
Nice catch @yshwanth 

I was able to replicate it:

- start a fresh install of bull wallet 
- goto testnet mode
- receive some funds
- open tx details 
- click txid for mempool web view
- go back 
- return to main net mode
- WALLET WILL BE GONE!

**Comment by i5hi** [comment]
> Nice catch @yshwanth
> 
> I was able to replicate it:
> 
>     * start a fresh install of bull wallet
> 
>     * goto testnet mode
> 
>     * receive some funds
> 
>     * open tx details
> 
>     * click txid for mempool web view
> 
>     * go back
> 
>     * return to main net mode
> 
>     * Lands on create wallet page
> 
> 
>     * EDIT: Wallet is not removed. It's still there on restart. So much be just a router issue.

This seems to have gotten fixed over the past few releases. 

Just tested this flow and not able to replicate it anymore.
