### ISSUE TITLE
Bottom button overlaps with label fields on import screens when typing

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#233]
App version : 0.1.98- 1.1

Description : On recover backup and create new wallet screens, the bottom button overlaps with label text field when typing.

![signal-2024-01-22-23-36-05-545.jpg](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/42468133/f5760997-09cc-4a77-b38f-e670a170a42b)

**Comment by i5hi** [comment]
@yshwanth This happens on several pages. Please check and share all the pages this is happening on.

**Comment by yshwanth** [comment]
Pages that had these issues
1. Create new wallet 
2. Recover backup
