### ISSUE TITLE
Coin control - Can select coins multiple times

### ISSUE THREAD

**Issue by JuanOfTheNorth** [SatoshiPortal/bullbitcoin-mobile#234]
SETUP
Version : 0.1.98.-1.1
New wallet (fresh download)
Received 3 coins (200k, 300k, 500k)
On coin control screen 

- selected all 3 coins
- amount selected = 1M
- waited a few seconds and/or clicked around

ISSUES
- coins are available again
- reselected all 3 coins
- amount selected = 2M

Proceeded to signing screen
- coins selected = 6
- amount selected = 2M

RESULT
- Proceeded to sending screen
- App did not allow spend and gave proper error when trying too large an amount.

*Not related to #224 as above tests were also happening on that wallet.

**Comment by i5hi** [comment]
Hey @JuanOfTheNorth ! Thanks for the report!

We have been in the middle of a major upgrade of the entire wallet UX hence the old issues (primarily coin selection) have not been properly addressed yet. We will be revisiting them all over the coming weeks.

**Comment by i5hi** [comment]
Hey @JuanOfTheNorth 

This should be fixed in 0.2.2. If you find any issues let us know or you can close the issue.

**Comment by JuanOfTheNorth** [comment]
This appears resolved now. Thank you
