### ISSUE TITLE
[App crash] When sending tx with Bull bitcoin electrum server

### ISSUE THREAD

**Issue by saiy2k** [SatoshiPortal/bullbitcoin-mobile#239]
App is crashing when sending tx / just fetching txs when connected with bull bitcoin electrum.
When connected with blockstream electrum, app is working good.

Build from bbe181b59f9d2a5f5f5a91b4f5cd7d21f1c8be60

https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/4c387c73-bb7e-4274-b5cc-a1395e80c3d5

Guess there is some unhandled exception somewhere with electrum module.

Following log happens, when the app crashes:

Instance 1:
<img width="1079" alt="Screenshot 2024-02-23 at 7 19 15 AM" src="https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/4b361e69-83e9-4a7a-b86f-ae6aa2d38f68">

Instance 2:
<img width="1085" alt="Screenshot 2024-02-23 at 7 25 57 AM" src="https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/ef3f1b6d-9f17-49b0-bc5c-58c378fb1072">

Instance 3:
<img width="1337" alt="Screenshot 2024-02-23 at 11 10 13 AM" src="https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/701985/18af6199-8aa5-4f26-b0b2-ff6e31c718b0">

**Comment by i5hi** [comment]
This was an issue with the electrum server. Should be fine now.
