### ISSUE TITLE
Create/Import Default BullBitcoin Wallet

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#242]
On fresh app install a user is prompted to create or import a seed used for the following `default` wallets:

- Secure Bitcoin
- Instant Liquid

Swaps should only be allowed to/from these wallets.

This is different to `Imported` or `New Bitcoin` wallets - which is now accessible through Settings and is considered an advanced feature.

![Image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/20156932/cdf3b312-1f2b-4294-8ffc-94b52d9131ba)

**Comment by mocodesmo** [comment]
@i5hi are we waiting to integrate lwk before implementing this ?
also pls review the required updates below 

-------------------

onappstart

UI
- if no main wallets show red screen
- red page - buttons to updated import/create logic

BLOC
- import 
	- straight to recover
	- flag for main wallet
	-  onsave - create 2 wallets (secure + instant )
- create
	- flag for main wallet
	- onsave - create 2 wallets (secure + instant )

PKG
- wallet repository
	- check for main existing 
	- change main wallet property to true

MODEL
- main wallet - bool

**Comment by i5hi** [comment]
> send+receive

    only when main wallet selected show swap ui

Its the reverse, only when swap is selected (user choses Lightning as payment option) show only main wallets as options

**Comment by i5hi** [comment]
lwk wallet creation has been added by Sai.

wallet/sensitive/create.dart

`oneLiquidFromBIP39`

**Comment by i5hi** [comment]
Notes: 

- Default wallets should not be labelled by user. It should be called Instant/Secure for Liquid/Bitcoin.
- Default wallets should always be bip84 (do not allow wallet selection)

**Comment by i5hi** [comment]
@mocodesmo

**Comment by i5hi** [comment]
Import still shows wallet selection page. It should just automatically use bip84.
