### ISSUE TITLE
Integrate lwk into bullbitcoin-mobile

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#243]
Update `model` and `pkg` to support a liquid wallet.

Keep functions and types ready for integration in bloc when UI work begins.

**Comment by i5hi** [comment]
- [ ] New/Import Wallet
- [ ] Sync
- [ ] Balance
- [ ] Transactions
- [ ] Addresses (Receive)
- [ ] Send

**Comment by mocodesmo** [comment]
not completed yet

**Comment by i5hi** [comment]
@saiy2k Please test send flow, if we have issues we can address them in lwk-dart, if its all good we can close this issue.
