### ISSUE TITLE
[Add Feature] Decode Bolt11 Invoice 

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#261]
https://github.com/lightning/bolts/blob/master/11-payment-encoding.md

**Comment by BullishNode** [comment]
https://github.com/MutinyWallet/bitcoin-waila

**Comment by BullishNode** [comment]
Check the Liqiud Address branch
https://github.com/MutinyWallet/bitcoin-waila/pull/14

**Comment by mocodesmo** [comment]
@yshwanth  this is already implemented. 
Not sure what you're trying to imply here.

https://github.com/SatoshiPortal/bullbitcoin-mobile/blob/5b476ad3d73a4bb13743a94e18ce27e2680ed8f2/lib/_pkg/boltz/swap.dart#L21

**Comment by yshwanth** [comment]
Not implemented in UI Send screen but implemented on boltz dart code 👍

**Comment by mocodesmo** [comment]
thank you for your contributions  👍

https://github.com/SatoshiPortal/bullbitcoin-mobile/blob/5b476ad3d73a4bb13743a94e18ce27e2680ed8f2/lib/send/bloc/send_cubit.dart#L153
