### ISSUE TITLE
[Logs] Error occurred while sync wallet 

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#272]
App version: https://github.com/SatoshiPortal/bullbitcoin-mobile/commit/7e4226a68a2e086a608c2c6880a9bd53cb3e7449

Description: On Liquid receive, the transaction is success, but there is error on wallet sync 

Error: Error occurred while syncing wallet
 -- unexpected end of file (multiple types)
 
 Note: Using bullbitcoin electrum server, above error persists. But with blockstream server, no issue

**Comment by i5hi** [comment]
electrum server related.
