### ISSUE TITLE
[Liquid Receive] Transaction ID and Recipient address has invalid info

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#273]
App version : https://github.com/SatoshiPortal/bullbitcoin-mobile/commit/7e4226a68a2e086a608c2c6880a9bd53cb3e7449

Description: Redirecting on click of Transaction ID to liquid mempool has invalid
This issue happened due to electrum server issue 

Note: Able to verify transaction ID on mempool.space and blockstream.info

**Comment by i5hi** [comment]
We need to use `https://blockstream.info/liquidtestnet/` for testnet and `https://blockstream.info/liquid/` for mainnet. 

OR

`https://liquid.network/testnet/` & `https://liquid.network/`

Address, need to be fixed. Currently showing ScriptPubKey.
