### ISSUE TITLE
[Receive] Page goes blank

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#277]
App version: https://github.com/SatoshiPortal/bullbitcoin-mobile/commit/5a7f0712275bf2ec4f218030a7225f3e88f6b664

Description: Switching from Instant wallet to secure wallet on Invoice Receive page goes blank

Steps to reproduce:
Testnet
Receive -> Instant via Lightning -> Create a swap -> Get Invoice
Change to Secure Wallet
Observe: Page goes blank

**Comment by i5hi** [comment]
can you reinstall the app and try reproduce this? because it does not happen all the time.

**Comment by yshwanth** [comment]
Resolved. Closing this issue
