### ISSUE TITLE
[Addresses] Liquid address link redirect to bitcoin mempool

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#279]
App version: https://github.com/SatoshiPortal/bullbitcoin-mobile/commit/8a1fa7bec4773104c8bd3092f08e4f607a08823f

Description: Addresses in Liquid/Instant wallet redirect to bitcoin mempool instead of liquid

Note: Liquid Tx page address redirect has no issue

**Comment by saiy2k** [comment]
This is fixed and pushed to main @ fe3180e6e3335fe0131cd2e8ce087428c53fcab6

**Comment by yshwanth** [comment]
Will test and close this issue

**Comment by yshwanth** [comment]
Resolved
