### ISSUE TITLE
[Tx Homepage] Liquid tx that is unconfirmed is showing up as confirmed

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#282]
App version: https://github.com/SatoshiPortal/bullbitcoin-mobile/commit/246e85cb54c88dbb60c011f8d43850e728afd78d

Description:  Liquid transaction that is unconfirmed in mempool is showing up as confirmed

**Comment by i5hi** [comment]
we have to use lwk height field to check if tx is confirmed or not.
