### ISSUE TITLE
[Instant wallet] Liquid tx isn't showing in Transaction list on Home

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#289]
Description : Unable to see Transaction tx received from liquid wallet in Transaction list in home
Error logs :  Unable to sync liquid wallet

**Comment by BullishNode** [comment]
Very vague can you elaborate?

**Comment by yshwanth** [comment]
This issue happened once but I can't recreate this isuue.

**Comment by i5hi** [comment]
Maybe your network connection or you were on an old version and did not run `flutter packages upgrade` - run this by default everytime you pull from main.

Patches happening every few days in `lwk-dart` and `boltz-dart`

**Comment by i5hi** [comment]
Please close the issue if the problem is resolved.
