### ISSUE TITLE
Support scanning bip21 unified qr code

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#298]
Scanning a bip21 unified qr doesn't detect lightning invoice. It only detects on chain address

**Comment by BullishNode** [comment]
Related issue: https://github.com/SatoshiPortal/bullbitcoin-mobile/issues/247#issue-2242310121

**Comment by michael1011** [comment]
Why is this not planned?

**Comment by yshwanth** [comment]
As it already reference in another issue in detail, so closed it.
