### ISSUE TITLE
Create new wallet using existing mnemonic and new bip39 passphrase

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#3]
Currently, the app allows the user to create a new wallet but will automatically generate a new mnemonic for this wallet.

We should add a new wallet creation flow which takes an existing wallet's mnemonic and creates a new wallet with that mnemonic and a passphrase.

The flow should be as follows:

1. User selects "create new wallet"
2. A new screen shows two options:
- create new wallet seed
- add passphrase to wallet seed
3. If "add passphrase to wallet seed" option is selected, a third screen displays all the wallet seeds that the wallet is aware of (created by the Bull Bitcoin app or imported by the user)
4. User selects the wallet seed
5. On a 4th screen, we display a input field for a bip39 passphrase
6. From that bip39 passphrase and the mnemonic selected by the user, we create a new wallet.

**Comment by i5hi** [comment]
Is this the Recover flow? 

User is able to now Recover a spending wallet using an external bip39 mnemonic and passphrase and then choose whether to Recover either bip44/49/84 wallets from it.

**Comment by i5hi** [comment]
Closing this. It ill be covered in #39
