### ISSUE TITLE
[LnUrl] Add support

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#315]
Both, LNURL pay and LNURL withdraw, can be supported

## LNURL pay LUD-06

Reference: https://github.com/lnurl/luds/blob/luds/06.md

Can be implemented by:

1. Fetching an invoice for the desired amount on the client from the LNURL sever
2. Creating a swap with that invoice

### Implementation notes

[Lightning Addresses](https://github.com/andrerfneves/lightning-address/blob/master/README.md#tldr) should also be implemented. They are very similar to LUD-06. The only difference being that instead of decoding the LNURL string, a REST API call is being done.

## LNURL withdraw LUD-03

Reference: https://github.com/lnurl/luds/blob/luds/03.md

Can be implemented by:

1. Create a reverse swap with the desired amount
2. Giving that invoice to the LNURL server

_Originally posted by @michael1011 in https://github.com/SatoshiPortal/bullbitcoin-mobile/issues/313#issuecomment-2231121996_

**Comment by i5hi** [comment]
[dart_lnurl](https://pub.dev/packages/dart_lnurl)

**Comment by michael1011** [comment]
> [dart_lnurl](https://pub.dev/packages/dart_lnurl)

That package was published by bottlepay which does not exist anymore, so be careful; you might want to fork it

**Comment by i5hi** [comment]
@michael1011 i am wondering if we should add lnurl support via the boltz-rust/dart package

**Comment by michael1011** [comment]
> i am wondering if we should add lnurl support via the boltz-rust/dart package

Yes imho

**Comment by i5hi** [comment]
Thanks for the help @michael1011 !
