### ISSUE TITLE
Recover Wallet Bugs

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#32]
Few bugs and nits regarding recover wallet flow:

- [x] Wallet is not created properly. Currently there is no wallet data shown and I am not able to trigger a sync by dragging down the screen. I assume there is an error with how the wallets descriptor is being constructed. Fix should display the synced wallet data (balance and txs) from previous step on returning home.

- [x] If a wrong word is used the Recover button stops working even if the spelling of the word is corrected. To reproduce, type in a correct seed and change the spelling of one, click Recover, correct the spelling and click Recover again.

- [x] If a user goes back after typing words (while 3 potential wallet types are loading) - app freezes - possible something to do with the sync call made to load the potential wallets.

- [x] when a user types the words, help them finish it with filtered suggestions from the bip39 word list

- [ ] Users are shows the seed in a different ordering to how they have to end up typing it for Recovery or Testing

Typing the seed correctly on first try alone works. However, after wallet is created and return to the Home Screen, there are a few more bugs:

How we display it for users to write:
```
1. word1          5. word5
2. word2         6. w6
3. w3               7. w7
4. w4               8. w8
```
How we display it for users to type:
```
1. word1          2. word2
3. word3         4. w4
5. w5               6. w6
7. w7               8. w8
```

**Comment by i5hi** [comment]
Good reference is sparrow wallet. Their Recover from mnemonics flow is perfect.

Since on mobile enter == done, we can consider a UX where we wait until what the user has typed arrives at the last word in the filtered bip39 list and automatically select it and move to the next entry.

**Comment by i5hi** [comment]
Sparrow is desktop only, so they use the Enter key to complete the word selection

**Comment by i5hi** [comment]
Typing the seed correctly on first try alone works. However, after wallet is created and return to the Home Screen, there are a few more bugs:

- [ ] Display the synced wallet data (balance and txs) from previous step. Currently there is no wallet data shown and I am not able to trigger a sync by dragging down the screen. I assume there is an error with how the wallets descriptor is being constructed.

**Comment by i5hi** [comment]
@mocodesmo will need your help clearing the last task regarding ordering of seed words.

**Comment by mocodesmo** [comment]
Recovery is now reordered and selecting ENTER will go to the next word field  
dbe63b66e427882eb11648c10e8adadc8195d198
