### ISSUE TITLE
[Custom Fee Selection] Custom value not being caputured

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#331]
When a custom fee value is typed in fee selection, it is not actually used in building the transaction.

**Comment by kumulynja** [comment]
@i5hi This should be fixed by https://github.com/SatoshiPortal/bullbitcoin-mobile/pull/348.

**Comment by i5hi** [comment]
Cheers!

**Comment by kumulynja** [comment]
@i5hi I accidentally closed my previous PR and it wasn't merged to main yet, I made a new one here: https://github.com/SatoshiPortal/bullbitcoin-mobile/pull/363
Sorry for the confusion.
