### ISSUE TITLE
[Send] bip49 addresses in QR are being converted into lowercase when scanned 

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#334]
Example: 3Fz8Lj3pjGprg2nnZByXrGMhUGd1yPpn6E

**Comment by kumulynja** [comment]
@i5hi https://github.com/SatoshiPortal/bullbitcoin-mobile/pull/355 fixes this.

**Comment by i5hi** [comment]
Cheers!

**Comment by kumulynja** [comment]
@i5hi The fix didn't got merged to main yet, I accidentally closed the PR, I opened a new one here now: https://github.com/SatoshiPortal/bullbitcoin-mobile/pull/362
Sorry for the confusion.
