### ISSUE TITLE
Wallet will lists balance, outgoing transactions but not received transactions

### ISSUE THREAD

**Issue by DanGould** [SatoshiPortal/bullbitcoin-mobile#340]
I'm finding this issue in `syncWalletOld`. Only seeing "No Transactions yet" despite a balance being displayed. In `BDKTransactions.getTransactions()`, `storedTx` is `null`, so the following line `updatedTx = Transaction(...` returns without being handled and sync never completes.

![image](https://github.com/user-attachments/assets/835be9fb-1be6-4a7d-9ad2-72fbddd68abe)

**Comment by HLeach-Tech** [comment]
> I'm finding this issue in `syncWalletOld`. Only seeing "No Transactions yet" despite a balance being displayed. In `BDKTransactions.getTransactions()`, `storedTx` is `null`, so the following line `updatedTx = Transaction(...` returns without being handled and sync never completes.
> 
> ![image](https://private-user-images.githubusercontent.com/8525467/395320597-835be9fb-1be6-4a7d-9ad2-72fbddd68abe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMzY5ODUsIm5iZiI6MTczNDAzNjY4NSwicGF0aCI6Ii84NTI1NDY3LzM5NTMyMDU5Ny04MzViZTlmYi0xYmU2LTRhN2QtOWFkMi03MmZiZGRkNjhhYmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTJUMjA1MTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWFkOGUyNTMzZmVkOTZlYTVjMDg1ZTY4MTIyZDQyZDMxODc4MjczMmYyNGEwMzAyZTJhNTkwNmFlZjVlNjRlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.wja_kMPrtSe_mFFUGLFG1Nnmb5GcM6Bs6srDIiaOhsg)


Hello @DanGould 
You’re experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID BTC12096
Please see the link below to our dedicated support line:
[Bull Bitcoin Network DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by DanGould** [comment]
Strangely, after sending a transaction, I do suddenly get a history:

![image](https://github.com/user-attachments/assets/9db7667a-acb5-42b3-9a58-3edad8679fc7)

However, you might note that it's missing the initial funding transaction. It's not telling me when or wherethe 0.6 BTC balance came from.

**Comment by kumulynja** [comment]
I found some conversion issues that threw an error in the `getTransactions` function and fixed it here to get the transaction history to show: https://github.com/SatoshiPortal/bullbitcoin-mobile/pull/342.

**Comment by i5hi** [comment]
Thanks @kumulynja !
