### ISSUE TITLE
[Payjoin] New wallet cannot payjoin since there are no UTXOs

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#357]
Do no allow a wallet with no utxo's to generate a payjoin address since there are no utxos.

A warning should be displayed in the receive page and a normal address should be shown instead of a payjoin address.

**Comment by ethicnology** [comment]
commit 253c5c68d3eeb15ebdadb70969fc7877c18e301c is contained in PR #344
