### ISSUE TITLE
[Testnet] Network Fees shows up as 0 in Transaction List

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#359]
<img width="404" alt="Screenshot 2024-12-17 at 4 53 46 PM" src="https://github.com/user-attachments/assets/0c689599-be85-4967-a872-0d4cdc9207ff" />

**Comment by ethicnology** [comment]
I can't reproduce
<img width="390" alt="Capture d’écran, le 2024-12-17 à 09 48 53" src="https://github.com/user-attachments/assets/4de31eca-be5e-4a09-a23f-a8c1053d4f8a" />


Is it on a specific branch?

**Comment by ethicnology** [comment]
@i5hi should we close this one?

**Comment by ethicnology** [comment]
Can't reproduce on testnet

<img width="407" alt="Capture d’écran, le 2024-12-30 à 08 16 03" src="https://github.com/user-attachments/assets/0dfe8f31-f950-4d6b-8dc8-f72a45dd4ad1" />
