### ISSUE TITLE
[Payjoin] SendPayjoin Issues

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#361]
For a payjoin send:
- [x] when a payjoin address is pasted the UI should mention that the transaction is a payjoin on the build tx page
- [x] the build process should be separated from the confirm process and we should have a screen to confirm the details
- [x] after confirm there should be a status page for the payjoin (similar to swaps) - there is an option to exit and go to the transaction detail page or go back home
- [x] there should be a toast that notifies the user when a payjoin broadcasts

**Comment by DanGould** [comment]
- [ ] uri & address copy / paste should be separate
- [ ] Make historic transfer amounts accurate by taking the difference of sent and received
