### ISSUE TITLE
[Payjoin Receive] After creating a payjoin address for Bitcoin, the same address is used under the Liquid tab

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#371]
<img width="345" alt="Screenshot 2024-12-22 at 1 23 23 PM" src="https://github.com/user-attachments/assets/0e005dab-f3ca-4f3c-ae78-dc8f5747a040" />
<img width="343" alt="Screenshot 2024-12-22 at 1 23 30 PM" src="https://github.com/user-attachments/assets/849113cf-0440-41bd-b27f-1b88021704d6" />

**Comment by kumulynja** [comment]
This should be fixed by: https://github.com/SatoshiPortal/bullbitcoin-mobile/pull/375
