### ISSUE TITLE
[Testnet] For 'Liquid to Liquid' , 'Liquid to Lightning' and 'Liquid to On-chain Swap' transactions observing LwkError (Error occurred while broadcasting transaction).

### ISSUE THREAD

**Issue by kiranmetri** [SatoshiPortal/bullbitcoin-mobile#386]
![Screenshot_20241224-181835](https://github.com/user-attachments/assets/aac5a343-8483-4320-a22e-0b6c974d268b)
![Screenshot_20241224-175430](https://github.com/user-attachments/assets/08d443fc-397e-460f-ae80-4491c9244fe6)

**Comment by i5hi** [comment]
Use electrum's blockstream server

**Comment by i5hi** [comment]
Use custom url:

`blockstream.info:465`

I will update the config - it currently has a bad url

**Comment by kiranmetri** [comment]
Issue is resolved on the latest APK (v0.3.8)
