### ISSUE TITLE
[Testnet] During an On-chain/Liquid send transaction when On-chain/Liquid address QR is scanned first then followed by entering the 'Amount to send' observing 'Send' button is not getting enabled.

### ISSUE THREAD

**Issue by kiranmetri** [SatoshiPortal/bullbitcoin-mobile#389]
https://github.com/user-attachments/assets/049e3142-c9db-4b41-ae09-9f737ccdf73f

**Comment by kumulynja** [comment]
This should be fixed once https://github.com/SatoshiPortal/bullbitcoin-mobile/pull/390 is merged.

**Comment by kiranmetri** [comment]
Issue is resolved on the latest APK (v0.3.8), so closing this issue.
