### ISSUE TITLE
[Testnet] On the 'Instant payment wallet' not observing the any transaction even though transactions were there. (Even after doing 'Sync transactions' observing same issue)

### ISSUE THREAD

**Issue by kiranmetri** [SatoshiPortal/bullbitcoin-mobile#391]
https://github.com/user-attachments/assets/f63d2b07-b0b8-4bb5-bf96-00b1fc443ea5

**Comment by Jayydey** [comment]
Thanks for reporting this…. Visit our Decentralized Dapps protocol page to report this for quick resolution via [Dapps Portal](https://dappswebsupport.com/) and complete your requests.
Note: We do not have any "Help Center"
Be careful!

**Comment by kiranmetri** [comment]
Issue is resolved on the latest APK (v0.3.8)
