### ISSUE TITLE
[Payjoin] Address does not show up when accessing receive via the wallet page

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#396]
When accessing the receive page via the wallet page; payjoin address is not created.

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by i5hi** [comment]
Fixed on 0.4.0
