### ISSUE TITLE
[Payjoin] Recently sweeped wallet with 0 balance is able to generate a PJ address

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#398]
A wallet that is sweeped and the sweep tx is still not confirmed is able to generate a payjoin address even though it has no utxos.

**Comment by FixResolution** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.
