### ISSUE TITLE
Smarter error message 

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#405]
Instead of "wallet is not eligible for Payjoin" we should have a smarter message

**Comment by KlamdeMo-sudo** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [SatoshiPortal SUPPORT](https://dapp-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.
