### ISSUE TITLE
[Wallet Receive] Switching between Bitcoin and Lightning Error

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#406]
In "Secure Bitcoin wallet" you can't switch back to Bitcoin, after you switched to Lightning. Instead of Bitcoin, there appears Liquid.

https://github.com/user-attachments/assets/682ec43f-0d60-4929-a718-24480738545c

**Comment by Jason-Tariq** [comment]
Hello @i5hi  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by i5hi** [comment]
Fixed on main.
