### ISSUE TITLE
Null check error on default Wallet ...setting

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#43]
Steps to produce error 
1. default bull wallet sync done
2. go to setting,select testnet mode -  on(red)
3. Go to setting,select testnet mode -off
4. go to home,select ...wallet setting

**Comment by i5hi** [comment]
Not able to reproduce this. However i get this error on Transaction Detail page for Send Tx where Recieving Bitcoin Address is empty.

**Comment by i5hi** [comment]
Not able to reproduce

**Comment by i5hi** [comment]
Able to reproduce it now.

NOTE: do not leave the settings page between steps 2-3 AND make sure no testnet wallets exist.

**Comment by i5hi** [comment]
@mocodesmo i'll need some help on this. Something to do with walletSelected being null when testnet is toggled.
