### ISSUE TITLE
[Unhandled Exceptions] On app startup

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#48]
Pricer api fails on some calls and throws an exception that isnt handled properly.

**Comment by mocodesmo** [comment]
this seems to be only happening when EUR price is requested 



![Image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/5087609/eb0736ad-034e-4400-82df-78a089611282)

**Comment by i5hi** [comment]
Let's remove the request for now then?

**Comment by i5hi** [comment]
Now we have a new error on start up `Address Lookup Error` for all calls to servers - mempool and pricer

**Comment by i5hi** [comment]
Pricer does not error anymore so I have updated the name of this issue instead of creating a new one.

**Comment by mocodesmo** [comment]
@i5hi i think we can close this
