### ISSUE TITLE
Background snapshots protection

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#5]
A task-switcher function on mobile devices shows a screenshot of the app's most recent state. However, this snapshot can reveal private data. The secure_application package is made to prevent on-demand viewing of application material.

Include secure application constructor(SecureGate) is directly inside the MaterialApp by using its builder, above your app navigator.

**Comment by i5hi** [comment]
@mocodesmo We should make this easy to enable/disable so that we can turn it on for release builds and off for debug builds.

**Comment by mocodesmo** [comment]
@i5hi  disabled for debug mode

**Comment by i5hi** [comment]
@mocodesmo I misunderstood from the title, the `allow in debug/disable in release` is for `SCREENSHOT` not snapshot. What @BullishNode mentioned should be disabled even in debug builds.
