### ISSUE TITLE
Unable to change Tx label

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#57]
Cannot change Transaction label

**Comment by BullishNode** [comment]
Yeah sure. Should be possible yes. However, this may not update the Bitcoin address labels linked to that transaction.

**Comment by mocodesmo** [comment]
@i5hi this was updated on monday pls review

**Comment by i5hi** [comment]
unable to test this currently because of https://github.com/SatoshiPortal/bullbitcoin-mobile/issues/118
