### ISSUE TITLE
Recover wallet should support 24 words

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#60]
Option for selecting 12/24 words for both Create new wallet and Recover

**Comment by i5hi** [comment]
Thanks for the suggestion @yshwanth !

We will add this in the next release.

**Comment by i5hi** [comment]
@yshwanth if you want to attempt this use these guide lines.


- We only want to see 12 words on the screen at a time.
- Add two buttons under the word list to slide between two pages, each having a set of 12 words

1.      7.
2.     8.
3.     9.
4.     10.
5.     11.
6.     12.

<12      24>

RECOVER

**Comment by i5hi** [comment]
The UI will likely see an update, but for now this seems like the fastest way to get this functionality in.

**Comment by i5hi** [comment]
Thanks for the PR @yshwanth !

Closing this.
