### ISSUE TITLE
Wallet details screen

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#62]
This is what I propose for the wallet details screen, which will replace the "xpub" and "descriptors" screens

Note: the xpub and the descriptor should also have a copy button 

![image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/75800272/c5cfc232-1c27-4e0a-8042-1eef7318ad06)

**Comment by i5hi** [comment]
I also suggest we show the xpub in SLIP132 format (x/y/zpub) here since many wallets use this to import watch-only wallets.

**Comment by BullishNode** [comment]
@mocodesmo missing derivation path

**Comment by i5hi** [comment]
@mocodesmo only pending update is showing the slip pub key. 

If we show xpub let it include the keysource [fingerprint/hdpath]xpub
Slip key can be only the x,y,zpub

**Comment by i5hi** [comment]
Updated, but likely has bugs, requires testing.

**Comment by mocodesmo** [comment]
works fine with seed and xpub wallet
