### ISSUE TITLE
Refresh wallet balance after send

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#65]
Make sure to refresh wallet balance after send

**Comment by BullishNode** [comment]
This possibly just requires testing

**Comment by mocodesmo** [comment]
yes, currently sync is being called right after broadcasting the tx
do u think waiting a second after broadcast and before calling sync will improve the user's experience ? @BullishNode

**Comment by BullishNode** [comment]
I don't think it was just to make sure that we do the sync

**Comment by i5hi** [comment]
Closing this. I think this is addressed now by 0.1.91
