### ISSUE TITLE
Homepage UI

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#67]
-> Replaces "Spendable" by "Spendable on-chain" (to differentiate with Lightning later)
-> Changes the design of the backup warning message
-> Changes font of the "Transactions" header
-> If all transactions are confirmed, make the header just "Transactions"
-> If some transactions are unconfirmed, show "confirmed transactions" and "unconfirmed transactions" headers
-> Adds label under the amount field
-> Puts the time field on the right
-> Changes the arrow format (straight up or straight down instead of angle)
-> Removes the "+" or "-" sign in front of amount
-> Removes space in between list items
-> Removes "Wallet" and "Market" footers
-> Changes send and receive button styles
-> Adds the profile icon top right

**Notes**

-> Make sure that the order is newest at top

![image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/75800272/86b8539e-d0ae-49ae-91bd-699e4bcd4196)

![image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/75800272/93f8334d-43e5-49f9-ab54-c0cfdd4374ed)

**Comment by mocodesmo** [comment]
@i5hi need u to check the labels under each tx
@BullishNode will add user icon once we integrate with exchange features

the rest is ready on main

**Comment by BullishNode** [comment]
@mocodesmo I was thinking we could add the user icon to replace the "market" icon we had. With just the message saying exchange coming soon

**Comment by i5hi** [comment]
Updated.
