### ISSUE TITLE
Electrum server UI 

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#68]
-> Removes stopgap, retry and timeout configs (let's just use the defaults)
-> Shows which electrum server is connected
-> Shows if electrum server is connected for not (green = conncted, red = not connected)
![image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/75800272/e62a261e-159f-4543-a9ce-e095a4806fd7)

**Comment by i5hi** [comment]
Related to https://github.com/orgs/SatoshiPortal/projects/7?pane=issue&itemId=32109099

@BullishNode check out the comment on the above issue. We need those options for certain cases. We could hide them behind an `Advanced` button.

**Comment by BullishNode** [comment]
Duplicate
