### ISSUE TITLE
Fee selection UI

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#69]
-> time estimates
-> CAD fee estimates
-> Clarify that the fee is in sats/vbyte

![image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/75800272/ccda28a1-ef07-4ac0-8ca0-8af45b31c913)

**Comment by BullishNode** [comment]
For reference the fiat amount is based on a default config of 140 vbytes, as it is the standard for Mempool

Calculation for fiat:

[(feerate * 140)/100000000] * fiat price

example:

- Assuming 10 sat/vbyte rate
- 140 constant
- 1 BTC = 100 000 000 sats
- Bitcoin price of $30,000

[(10 sat/vbyte * 140 vbytes )/10000000] * 30000 =  0.42$

![image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/75800272/dde967e5-0d80-4a8e-8483-ef1dfed1618d)

**Comment by i5hi** [comment]
Fixed in 0.1.89-02
