### ISSUE TITLE
Enforce incognito mode on keyboard for seed input

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#7]
use enableIMEPersonalizedLearning: false for keyboard when typing seed so that mnemonic words are not logged by GBoard.

Not sure about the equivalent on ios. Wasnt able to find it with a simple google search.

This is required when doing a wallet recovery.

**Comment by i5hi** [comment]
This is complete and can be closed.

**Comment by i5hi** [comment]
Done.
