### ISSUE TITLE
Send Bitcoin UI

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#71]
-> Replaces pop-up by a separate page
-> Larger font for Wallet name
-> Page name is Send bitcoin (top right)
-> Keep the currency selector as is (disregard what you see in the screenshot below)
-> Replace "Note to self" by "Label (optional)"
-> replace by "Enter private note" by "Enter a description"
-> Updates the coin selection view when coins have been selected

![image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/75800272/537614c2-d102-43a0-89f3-655f08013694)

![image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/75800272/9271617c-81b0-42a1-b8af-a48a799bf9f0)

**Comment by mocodesmo** [comment]
@i5hi need u to check the labels under each tx 
@BullishNode will add user icon once we integrate with exchange features

the rest is complete on main

**Comment by i5hi** [comment]
Comment ignored :)))
