### ISSUE TITLE
Amount entering UX 

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#72]
Currently, when entering an amount, the first numbered entered starts off as being the last decimal and subsequent numbers being entered add to that. This is not very intuitive.

When entering an amount, it should be like this.

To obtain 0.000123 user should type "0" "." "0" "0" "0" "1" "2" "3"

To obtain 1500.23 user should type "1" "5" "0" "0" "." "2" "3"

**Comment by i5hi** [comment]
The UX in Recieve -> Create Invoice inputs the amount well, lets use that format across the wallet.

@mocodesmo
