### ISSUE TITLE
Confirm transaction UI

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#73]
The confirm transaction box should remain a pop-up

It contains:

-> amount sent in Bitcoin
-> fiat equivalent (using preferred currency)
-> Recipient address
-> Network fee in Bitcoin
-> Network fee fiat equivalent (this is not an estimate, we use the size of the transaction)

I believe we don't need to change anything in the UI for this issue, I am just putting it here for reference.

![image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/75800272/71c57eed-045e-4431-b2c6-d23108f51540)

**Comment by i5hi** [comment]
@mocodesmo  same would apply for pre-Broadcast
