### ISSUE TITLE
Send bug when coin selection and full wallet balance options are used

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#77]
I am sending funds with 1 coin selected and full wallet balance selected.

I can see in the send card that:
-> Coins selected is correct
-> Amount selected is correct

I am trying to hit "send" but nothing happens.

**Comment by i5hi** [comment]
You cannot select coins when sending full balance, must be throwing an internal bdk error. @mocodesmo We need tol disable coin select if send full amount is selected.

**Comment by i5hi** [comment]
Fixed in 0.1.89
