### ISSUE TITLE
Recover/Import wallet show seed exists error

### ISSUE THREAD

**Issue by yshwanth** [SatoshiPortal/bullbitcoin-mobile#78]
This might be a bug when we're importing a seed with and without passphrase and it shows seed exists because its error in when trying to save the seed when it should have a special case for passphrase that ignores that error and just adds a passphrase to the existing seed.

**Comment by i5hi** [comment]
Thanks!

**Comment by RaviPatelGit** [comment]
![photo1695312265](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/33780523/d870bd2f-b1dd-4ba3-9cb2-5021d86931c6)
![photo1695312223](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/33780523/4f040de4-ba73-4e59-9448-c36a1806f118)

**Comment by RaviPatelGit** [comment]
I got these error while trying to import samourai wallet with 12 words and passphrase.

**Comment by i5hi** [comment]
Fixed in 0.1.87
