### ISSUE TITLE
In "send" transaction box, let user select amount in fiat instead of just sats and btc 

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#8]
When in the send screen, let user switch from SATS to BTC to PREFERRED CURRENCY (fiat)

When switching to preferred currency, show available balance in preferred currency.

The input amount should be in preferred currency.

In the background, we convert the input amount in the preferred currency (fiat) to Bitcoin.

We keep the "send confirmation" screen as is.

**Comment by i5hi** [comment]
@mocodesmo will need your help on this one.

**Comment by i5hi** [comment]
@BullishNode we have add this feature however the way input works needs review. 

It may be unintuitive to some but intuitive to others. The reason for this is because we have added formatting in the input box which adds commas every thousands *,000

**Comment by BullishNode** [comment]
Gonna wait to test until we have a final version of send page

**Comment by i5hi** [comment]
Closing this for now as we support entering amount in fiat and https://github.com/SatoshiPortal/bullbitcoin-mobile/issues/72
