### ISSUE TITLE
Backup instructions

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#85]
Whenever clicking on a "backup" button or warning message, we always start with this page as the first page of the backup flow.

There are two pages depending on whether or not the wallet has a passphrase.

Text:

(No passphrase)

- If you lose your 12 word backup, you will not be able to recover access to the Bitcoin Wallet.
- Without a backup, if you lose or break your phone, or if you uninstall the Bull Bitcoin app, your bitcoins will be lost forever.
- Anybody with access to your 12 word backup can steal your bitcoins. Hide it well.
- Do not make digital copies of your backup. Write it down on a piece of paper, or engraved in metal.
- Your backup is not protected by passphrase. Add a passphrase to your backup later by creating a new wallet. 

(passphrase)

- Your backup is protected by passphrase. 
- Without a backup, if you lose or break your phone, or if you uninstall the Bull Bitcoin app, your bitcoins will be lost forever.
- Anybody with access to both your 12 word backup **and** your passphrase can steal your bitcoins. Hide them separately.
- If you lose your 12 word backup **or** your passphrase, you will not be able to recover access to the Bitcoin Wallet. Both the 12 words and the passphrase are required.
- Do not make digital copies of your backup and passprhase. Write them down separately on a piece of paper, or engraved in metal.

![image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/75800272/9fa997af-8a09-4491-9574-9914b6880ed7)
![image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/75800272/fdbbfa75-7503-47b7-bbfd-a26c692cee36)

**Comment by i5hi** [comment]
@mocodesmo the text does not entire match and does not change based on whether passphrase exists or not.

**Comment by mocodesmo** [comment]
@i5hi 
this is working fine pls check again 
the text is copied from the bullet points on top not the screenshot

**Comment by i5hi** [comment]
@mocodesmo no passphrase wallet backup text is fine now.

Passphrase wallet backup content does not match.

For both cases, the checkbox does not work.

**Comment by i5hi** [comment]
Passphrase wallet unable to view backup.

`No Key` Error.

**Comment by i5hi** [comment]
Passphrase bug fixed.

**Comment by i5hi** [comment]
Content matches.
