### ISSUE TITLE
Send Bitcoin screen should be a page and not a pop-up

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#86]
![image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/75800272/fc9d0358-7243-488b-a279-8660f7b21004)
-> check the font / layout according to figma
-> make sure everything is aligned well

**Comment by i5hi** [comment]
Important the way the address is displayed!

It didnt feel good seeing just the end bit...
