### ISSUE TITLE
When a BIP21 description is added to invoice, make the private label the same as description

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#9]
I don't there there is really a need to have a BIP21 description that is different from a private label, when receiving payments.

So when we are creating a BIP21 invoice and if the user has entered a description, we can use that description as the private label. If anything, the user can always edit the label later. This will remove one extra step of adding a private label which may be confusing and also it will ensure that everyone that creates a BIP21 description has a private label.

**Comment by mocodesmo** [comment]
invoice description is now being used as address label and this reflects in addressbook
@i5hi  pls clean up AddressStatus are unset seems unneccessary

**Comment by i5hi** [comment]
Updated. Thanks @mocodesmo !
