### ISSUE TITLE
Address label popup and display on receive page

### ISSUE THREAD

**Issue by BullishNode** [SatoshiPortal/bullbitcoin-mobile#92]
It's easier to enter the address label with a save button as a pop-up.
When the label is saved, show it on the receive page for that address
![image](https://github.com/SatoshiPortal/bullbitcoin-mobile/assets/75800272/3393e9d9-8ed0-412b-87a2-73f4f1e320be)

**Comment by i5hi** [comment]
Fixed in 0.1.87
