### ISSUE TITLE
wallet-card throws exception in new design update

### ISSUE THREAD

**Issue by i5hi** [SatoshiPortal/bullbitcoin-mobile#97]
════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
There are multiple heroes that share the same tag within a subtree.

Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), each Hero must have a unique non-null tag.
In this case, multiple heroes had the following tag: wallet-card
Here is the subtree for one of the offending heroes: Hero
    tag: wallet-card
    state: _HeroState#13b72
When the exception was thrown, this was the stack

**Comment by mocodesmo** [comment]
fixed on main
